# Generated by Django 4.2.23 on 2025-07-26 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogger", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="blogs",
            new_name="Blog",
        ),
    ]
