# Generated by Django 4.2.23 on 2025-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0002_rename_blogs_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
